### ISSUE TITLE
Examples pied de poule

### ISSUE THREAD

**Issue by noorboekenoogen** [digital-craftsmanship/GOLDEN-RATIO#1]
Hi! 
I can't seem to find the example code for the pied de poule pattern discussed in lecture 7 on youtube. In the slides it's said that this code has to be in this repository. Am I in the wrong place then? 

Thanks in advance!

**Comment by leinelissen** [comment]
Hi Noor,

I'm checking in with Loe about this. I'll get back to you soon.

Lei

**Comment by leinelissen** [comment]
Hi Noor,

Thanks again for notifying us. You should now be able to be find the Processing code for lectures 7 and 8 in this repository. Good luck!

Lei
